name: socialmedia
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: 3.3.0
  circular_bottom_navigation: ^2.3.0
  cloud_firestore: ^4.9.3
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_crashlytics: ^3.3.7
  firebase_messaging: ^14.6.9
  firebase_storage: ^11.2.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: 2.0.7
  geolocator: ^10.1.0
  google_sign_in: ^6.1.5
  image: ^4.1.3
  image_picker: ^1.0.4
  meta: ^1.9.1
  path_provider: ^2.1.1
  timeago: ^3.5.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  assets:
    - assets/images/
