name: socialmedia
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cached_network_image: null
  circle_bottom_navigation: ^1.0.5
  cloud_firestore: ^0.14.4
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  firebase_auth: ^0.17.0-dev.2
  firebase_core: ^0.5.3
  firebase_crashlytics: ^0.2.4
  firebase_messaging: ^7.0.3
  firebase_storage: ^5.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_svg: null
  geolocator: ^6.2.1
  google_sign_in: ^4.1.1
  image: ^2.1.4
  image_picker: ^0.6.2+3
  meta: ^1.1.8
  path_provider: ^1.5.1
  timeago: ^3.2.2
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  assets:
    - assets/images/
